services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pytech-backend
    command: >
      sh -c "python manage.py migrate --noinput; daphne -b 0.0.0.0 -p 8000 pytech.asgi:application"

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - ollama

  db:
    image: pgvector/pgvector:pg15
    container_name: pytech-db
    restart: always
    environment:
      POSTGRES_USER: pytech_user
      POSTGRES_PASSWORD: pytech_pass
      POSTGRES_DB: pytech_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pytech-celery
    command: celery -A pytech worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend  
      - ollama  

  redis:
    image: redis:7
    container_name: pytech-redis
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: pytech-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama    

volumes:
  postgres_data:
  ollama_data:
